version: '3.8'
services:
  web_jenkins:
    image: node:18-slim
    container_name: fashionstore_jenkins
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin1234@cluster0.9p6bn71.mongodb.net/fashionstore?appName=Cluster0
      - JWT_SECRET=fashionstore123
      - PORT=5000
    restart: always
